# Generated by Django 2.2.2 on 2019-06-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitePessoalApp', '0002_remove_dadoscontato_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadoscontato',
            old_name='created_date',
            new_name='data',
        ),
    ]
