# Generated by Django 2.2.2 on 2019-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePessoalApp', '0003_auto_20190606_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscontato',
            name='nomeSis',
            field=models.CharField(default='Desconhecido', max_length=20),
        ),
    ]
