# Generated by Django 2.2.2 on 2019-06-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitePessoalApp', '0004_dadoscontato_nomesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscontato',
            name='nomeSis',
            field=models.CharField(default='desconhecido', max_length=20),
        ),
    ]
